name: Your Github Workflow name
on:
  workflow_dispatch:
  schedule:
    - cron:  '*/5 * * * *'

jobs:
  run-python-script:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v2
        with:
          python-version: '3.13.5'
      - run: pip install requests
      - run: python main.py
